_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_tools: 0
  adminimal_admin_toolbar: 0
  apigee_api_catalog: 0
  apigee_edge: 0
  apigee_kickstart_content: 0
  apigee_kickstart_customizer: 0
  apigee_kickstart_enhancement: 0
  automated_cron: 0
  basic_auth: 0
  better_exposed_filters: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  comment: 0
  components: 0
  config: 0
  contact: 0
  contextual: 0
  ctools: 0
  datetime: 0
  dblog: 0
  default_content: 0
  dynamic_page_cache: 0
  editor: 0
  email_registration: 0
  entity: 0
  entity_reference_revisions: 0
  field: 0
  field_ui: 0
  file: 0
  file_link: 0
  filter: 0
  fontawesome: 0
  hal: 0
  help: 0
  history: 0
  image: 0
  jquery_ui: 0
  jquery_ui_datepicker: 0
  jquery_ui_slider: 0
  jquery_ui_touch_punch: 0
  jsonapi: 0
  jsonapi_defaults: 0
  jsonapi_extras: 0
  key: 0
  link: 0
  media: 0
  media_library: 0
  menu_link_content: 0
  menu_ui: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  quickedit: 0
  rdf: 0
  responsive_image: 0
  search: 0
  serialization: 0
  shortcut: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  user: 0
  views_ui: 0
  forum: 1
  pathauto: 1
  views: 10
  paragraphs: 11
  apigee_devportal_kickstart: 1000
theme:
  bartik: 0
  seven: 0
  radix: 0
  apigee_kickstart: 0
profile: apigee_devportal_kickstart
